server:
  port: 9090

spring:
  application:
    name: mc-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 39.106.195.202:8848
  datasource:
    auth:
      #spring.datasource.url为默认JDBC连接属性。如果用多数据源，那么需要重写这个属性为spring.datasource.jdbc-url
      jdbc-url: jdbc:mysql://39.106.195.202:3306/mc-auth?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
      username: root
      password: qcmoke)[good](boy
      driver-class-name: com.mysql.jdbc.Driver
    system:
      jdbc-url: jdbc:mysql://39.106.195.202:3306/mc-ums?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
      username: root
      password: qcmoke)[good](boy
      driver-class-name: com.mysql.jdbc.Driver

  #redis配置
  redis:
    database: 0
    host: 39.106.195.202
    port: 6379
    password: qcmoke)[good](boy
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

#非对称加密秘钥库配置
encrypt:
  key-store:
    location: classpath:key/qcmoke.keystore
    alias: qcmoke
    password: 123456password
    secret: 123456secret


##配置mybatis plus
mybatis-plus:
  type-aliases-package: com.qcmoke.auth.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto                                         #MySql主键自增策略
      table-prefix: t_                                      #全局表前缀
  configuration:
    map-underscore-to-camel-case: true                      #开启驼峰式命名规则支持


oauth2:
  social:
    #认证成功进入的前段页面
    front-url: http://localhost:9527
    #本地oauth2对于social认证的client-id
    client-id: social
    #第三方认证配置列表
    source-list:
      - social-type: github
        client-id: a0d287406edbdb70394d
        client-secret: 0dc78340e6a563d562b29adc1d17d9816a9014f9
        redirect-uri: http://localhost:9070/auth/resource/social/callback/github
      - social-type: gitee
        client-id: e0b713dfda1c0b068b3b92c9691f178930f17cc4ce6ae0091e5ca2d5f639cf5a
        client-secret: c001ddc8dfdf7057d64511c5d5021ba35e4482570db8ce0ccb4448f7ddf386a8
        redirect-uri: http://localhost:9070/auth/resource/social/callback/gitee
      - social-type: qq
        client-id: 101448999
        client-secret: 1d958787a87559bad371c0a9e26eef61
        redirect-uri: http://www.merryyou.cn/login/qq
      - social-type: weixin
        client-id: wxd99431bbff8305a0
        client-secret: 60f78681d063590a469f1b297feff3c4
        redirect-uri: http://www.pinzhi365.com/qqLogin/weixin

#springboot admin监控信息
#如果Spring Boot Admin的服务端和客户端都注册到注册中心的情况下，客户端是不需要加服务端的spring.boot.admin.client.url的；注意：父工程的spring-boot-starter-parent依赖要放在 <parent>，下面的的信息才会在Spring Boot Admin显示完整
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    # 是否展示健康检查详情
    health:
      show-details: ALWAYS