server:
  port: 9090

spring:
  application:
    name: mc-auth-server
  datasource:
    auth:
      #spring.datasource.url为默认JDBC连接属性。如果用多数据源，那么需要重写这个属性为spring.datasource.jdbc-url
      jdbc-url: jdbc:mysql://localhost:3306/micro-cloud-erp-auth?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    system:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/micro-cloud-erp-system?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: mc-auth-server-9090
    prefer-ip-address: true


#非对称加密秘钥库配置
encrypt:
  key-store:
    location: classpath:key/qcmoke.keystore
    alias: qcmoke
    password: 123456password
    secret: 123456secret