server:
  port: 8081

spring:
  application:
    name: micro-cloud-erp-order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  #个性化定制
  instance:
    #服务实例id（application.name可以对应多个instance）
    instance-id: micro-cloud-erp-order-8081
    #显示前缀ip
    prefer-ip-address: true


security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://127.0.0.1:9090/user