server:
  port: 8030

## 数据源
spring:
  application:
    name: mc-pms-server
  cloud:
    nacos:
      discovery:
        server-addr: 39.106.195.202:8848
        ip: 39.106.195.202
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.195.202:3306/mc-pms?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: qcmoke)[good](boy

  #redis配置
  redis:
    database: 0
    host: 39.106.195.202
    port: 6379
    password: qcmoke)[good](boy
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

##配置mybatis plus
mybatis-plus:
  type-aliases-package: com.qcmoke.pms.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true                      #开启驼峰式命名规则支持
  global-config:
    db-config:
      id-type: auto                                         #MySql主键自增策略
      table-prefix: t_                                      #全局表前缀
      logic-delete-field: delete_status  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.qcmoke: info
