server:
  port: 81

spring:
  application:
    name: mc-oms-business-server
  cloud:
    nacos:
      discovery:
        server-addr: 39.106.195.202:8848


#feign注解支持hystrix服务降级处理
feign:
  hystrix:
    enabled: true

#网关超时时间配置(对于路由使用serviceId时生效)
ribbon:
  #请务器请求超时时间,设置为2秒
  ConnectTimeout: 2000
  #请求处理超时时间(服务器响应超时时间),设置为30秒
  ReadTimeout: 30000
hystrix:
  command:
    default:
      execution:
        isolation:
          ##线程隔离策略配置，官方推荐使用THREAD，即下游依赖的请求在一个单独的线程中隔离，这里为了解决feign转发时需要携带head信息,所以讲策略设置为SEMAPHORE，即下游依赖请求在当前调用线程中执行
          strategy: SEMAPHORE
          #建议配置Hystrix的超时时间要大于ribbon的超时时间，否则会在接口调用还未完成的时候直接进入回调方法
          thread:
            #hystrix超时时间，默认是1秒，设置为64秒。hystrix.default.timeoutInMilliseconds >= ribbon.ConnectTimeout +ribbon.ReadTimeout
            timeoutInMilliseconds: 32000