server:
  port: 9070

spring:
  application:
    name: mc-gateway-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro-cloud-erp-system?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 123456
  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        # 配置路由：1、id：路由的唯一标识，可以任意不重复的字符串；2、url：路由地址，表示指向的目标服务器地址；3、predicates：断言，标识进入url的请求条件；4、filters：过滤器，表示进入路由的过程中执行的过滤
        - id: mc-auth-server
          uri: lb://mc-auth-server
          predicates:
            - Path=/auth/**
          filters:
        - id: mc-ums-server
          uri: lb://mc-ums-server
          predicates:
            - Path=/system/**
          filters:
        - id: mc-oms-server
          uri: lb://mc-oms-server
          predicates:
            - Path=/order/**
          filters:
        - id: mc-oms-business-server
          uri: lb://mc-oms-business-server
          predicates:
            - Path=/order-business/**
          filters:
        - id: mc-wms-server
          uri: lb://mc-wms-server
          predicates:
            - Path=/stock/**
      default-filters:
        - StripPrefix=1