server:
  port: 9070

spring:
  application:
    name: mc-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        - id: mc-auth-server
          uri: lb://mc-auth-server
          predicates:
            - Path=/auth/**
          filters:
        - id: mc-ums-server
          uri: lb://mc-ums-server
          predicates:
            - Path=/system/**
          filters:
        - id: mc-oms-server
          uri: lb://mc-oms-server
          predicates:
            - Path=/order/**
          filters:
        - id: mc-oms-business-server
          uri: lb://mc-oms-business-server
          predicates:
            - Path=/order-business/**
          filters:
        - id: mc-wms-server
          uri: lb://mc-wms-server
          predicates:
            - Path=/stock/**
      default-filters:
        - StripPrefix=1