server:
  port: 9070

spring:
  application:
    name: mc-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      routes:
        # 配置路由：1、id：路由的唯一标识，可以任意不重复的字符串；2、url：路由地址，表示指向的目标服务器地址；3、predicates：断言，标识进入url的请求条件；4、filters：过滤器，表示进入路由的过程中执行的过滤
        - id: mc-auth-server
          uri: lb://mc-auth-server
          predicates:
            - Path=/auth/**
          filters:
        - id: mc-ums-server
          uri: lb://mc-ums-server
          predicates:
            - Path=/system/**
          filters:
        - id: mc-oms-server
          uri: lb://mc-oms-server
          predicates:
            - Path=/order/**
          filters:
        - id: mc-oms-business-server
          uri: lb://mc-oms-business-server
          predicates:
            - Path=/order-business/**
          filters:
        - id: mc-wms-server
          uri: lb://mc-wms-server
          predicates:
            - Path=/stock/**
      default-filters:
        - StripPrefix=1