server:
  port: 8020

## 数据源
spring:
  application:
    name: mc-oms-server
  cloud:
    nacos:
      discovery:
        server-addr: 129.204.185.161:8848
        ip: 129.204.185.161
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.204.185.161:3306/mc-oms?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: qcmoke)[good](boy

  #redis配置
  redis:
    database: 0
    host: 129.204.185.161
    port: 6379
    password: qcmoke)[good](boy
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

##配置mybatis plus
mybatis-plus:
  type-aliases-package: com.qcmoke.oms.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true                      #开启驼峰式命名规则支持
  global-config:
    db-config:
      id-type: auto                                         #MySql主键自增策略
      table-prefix: t_                                      #全局表前缀
      logic-delete-field: deleteStatus  #全局逻辑删除字段值(实体类的属性，而不是表的属性) 3.3.0开始支持(使用mp自带方法删除和查找都会附带逻辑删除功能 ,自己写的sql不会，但@result调动mybatisplus的函数，那么这个子函数也会加上,),统一了全局都是delete_status为逻辑删除字段,但如果实体类上有 @TableLogic 则以实体上的为准，忽略全局
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  level:
    com.qcmoke: info
