server:
  port: 81

spring:
  application:
    name: micro-cloud-erp-order-business

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: micro-cloud-erp-order-business-81
    prefer-ip-address: true