server:
  port: 81

#feign注解支持hystrix服务降级处理
feign:
  hystrix:
    enabled: true
#启用feign注解支持hystrix服务降级处理后，解决http head不能发送的问题
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE


spring:
  application:
    name: micro-cloud-erp-order-business


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: micro-cloud-erp-order-business-81
    prefer-ip-address: true

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://127.0.0.1:9090/resource/user
