server:
  port: 9080

spring:
  application:
    name: mc-monitor-server
  #加入security 让监控中心能够认证登录
  security:
    user:
      name: qcmoke
      password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 39.106.195.202:8848
        # 将本服务实例注册到服务中心时，在元信息中携带访问本服务使用的用户名和密码,否则在使用security的情况下，即使登录成功在获取监控中心自身的信息时无权限获取
        metadata:
          user:
            name: ${spring.security.user.name}
            password: ${spring.security.user.password}

#springboot admin 监控信息（spring-boot-starter-parent要放在 <parent>才会在Spring Boot Admin显示完整）
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    # 是否展示健康检查详情
    health:
      show-details: ALWAYS