server:
  port: 8080



## 数据源
spring:
  application:
    name: mc-ums-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro-cloud-erp-system?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 123456
  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka
#  instance:
#    instance-id: mc-ums-server-8080
#    prefer-ip-address: true

##配置mybatis plus
mybatis-plus:
  type-aliases-package: com.qcmoke.ums.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false