server:
  port: 8080

spring:
  ##热部署
  devtools:
    restart:
      enabled: true

  application:
    name: mc-ums-server
  cloud:
    nacos:
      discovery:
        server-addr: 39.106.195.202:8848
  datasource:
    #整合p6spy作sql性能，引入p6spy依赖后,需要修改driver和url即可，并在resources下添加spy.properties，在配置里可以自定义日志输出，实现MessageFormattingStrategy接口即可（P6spySqlFormatConfig）
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://39.106.195.202:3306/mc-ums?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: qcmoke)[good](boy

  #redis配置
  redis:
    database: 0
    host: 39.106.195.202
    port: 6379
    password: qcmoke)[good](boy
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000

##配置mybatis plus
mybatis-plus:
  type-aliases-package: com.qcmoke.ums.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto                                         #MySql主键自增策略
      table-prefix: t_                                      #全局表前缀
  configuration:
    map-underscore-to-camel-case: true                      #开启驼峰式命名规则支持


#springboot admin监控信息
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    com.qcmoke: debug
