server:
  port: 8080

## 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/micro-cloud-erp-system?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 123456

##配置mybatis plus
mybatis-plus:
  type-aliases-package: com.qcmoke.system.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false


#security:
#  oauth2:
#    client:
#      client-id: admin
#      client-secret: 123456
#    resource:
#      #资源服务器启动时会去鉴权中心获取公钥并完成验证
#      jwt:
#        key-uri: http://127.0.0.1:9090/oauth/token_key