server:
  port: 9070

spring:
  application:
    name: micro-cloud-erp-gateway

#网关配置
zuul:
  #路由转发配置
  routes:
    auth:
      url: http://localhost:9090
    system:
      url: http://localhost:8080
    order:
      url: http://localhost:8081
    stock:
      url: http://localhost:8082
  #敏感头过滤配置（默认敏感头信息Authorization、Cookie、Set-Cookie会被过滤，以至于不转发的，那么网关后的服务也就获取不到。如果要获取则设置zuul.sensitiveHeaders为空即可转发所有敏感头。）
  sensitive-headers:


###配置oauth2，通过client-id和client-secret到认证服务器认证并获取jwt签名的秘钥
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://127.0.0.1:9090/user

#      jwt:
#        #资源服务器启动时会去鉴权中心获取公钥
#        key-uri: http://127.0.0.1:9090/oauth/token_key

