server:
  port: 9527

spring:
  application:
    name: micro-cloud-erp-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: micro-cloud-erp-gateway-9527
    prefer-ip-address: true